alter table SCRUMIT_DEADLINES add constraint FK_SCRUMIT_DEADLINES_ON_TASK foreign key (TASK_ID) references SCRUMIT_TASK(ID);
create index IDX_SCRUMIT_DEADLINES_ON_TASK on SCRUMIT_DEADLINES (TASK_ID);
