alter table SCRUMIT_SPRINT add constraint FK_SCRUMIT_SPRINT_ON_COMMAND foreign key (COMMAND_ID) references SCRUMIT_TEAM(ID);
create index IDX_SCRUMIT_SPRINT_ON_COMMAND on SCRUMIT_SPRINT (COMMAND_ID);
