alter table SCRUMIT_TASK add constraint FK_SCRUMIT_TASK_ON_SPRINT_BACKLOG foreign key (SPRINT_BACKLOG_ID) references SCRUMIT_SPRINT_BACKLOG(ID);
create index IDX_SCRUMIT_TASK_ON_SPRINT_BACKLOG on SCRUMIT_TASK (SPRINT_BACKLOG_ID);
