alter table SCRUMIT_TASK_DURATION add constraint FK_SCRUMIT_TASK_DURATION_ON_TASK foreign key (TASK_ID) references SCRUMIT_TASK(ID);
create index IDX_SCRUMIT_TASK_DURATION_ON_TASK on SCRUMIT_TASK_DURATION (TASK_ID);
