alter table SCRUMIT_MEETING add constraint FK_SCRUMIT_MEETING_ON_SPRINT foreign key (SPRINT_ID) references SCRUMIT_SCRUM(ID);
create index IDX_SCRUMIT_MEETING_ON_SPRINT on SCRUMIT_MEETING (SPRINT_ID);
