alter table SCRUMIT_MEETINGS_TASK add constraint FK_SCRUMIT_MEETINGS_TASK_ON_MEETING foreign key (MEETING_ID) references SCRUMIT_MEETING(ID);
alter table SCRUMIT_MEETINGS_TASK add constraint FK_SCRUMIT_MEETINGS_TASK_ON_TASK foreign key (TASK_ID) references SCRUMIT_TASK(ID);
create index IDX_SCRUMIT_MEETINGS_TASK_ON_MEETING on SCRUMIT_MEETINGS_TASK (MEETING_ID);
create index IDX_SCRUMIT_MEETINGS_TASK_ON_TASK on SCRUMIT_MEETINGS_TASK (TASK_ID);
