alter table SCRUMIT_CONTACT add constraint FK_SCRUMIT_CONTACT_ON_STATUS foreign key (STATUS_ID) references SCRUMIT_CONTACTS_STATUS(ID);
create index IDX_SCRUMIT_CONTACT_ON_STATUS on SCRUMIT_CONTACT (STATUS_ID);
