alter table SCRUMIT_TRACKER add constraint FK_SCRUMIT_TRACKER_ON_PROJECT foreign key (PROJECT_ID) references SCRUMIT_TASK(ID);
create index IDX_SCRUMIT_TRACKER_ON_PROJECT on SCRUMIT_TRACKER (PROJECT_ID);
