alter table SCRUMIT_TASK add constraint FK_SCRUMIT_TASK_ON_PARENT_BUG foreign key (PARENT_BUG_ID) references SCRUMIT_TRACKER(ID);
create index IDX_SCRUMIT_TASK_ON_PARENT_BUG on SCRUMIT_TASK (PARENT_BUG_ID);
