alter table SCRUMIT_TRACKER add constraint FK_SCRUMIT_TRACKER_ON_PERFORMER foreign key (PERFORMER_ID) references SEC_USER(ID);
create index IDX_SCRUMIT_TRACKER_ON_PERFORMER on SCRUMIT_TRACKER (PERFORMER_ID);
