alter table SCRUMIT_PROJECT_ROLE add constraint FK_SCRUMIT_PROJECT_ROLE_ON_TEAM foreign key (TEAM_ID) references SCRUMIT_TEAM(ID);
alter table SCRUMIT_PROJECT_ROLE add constraint FK_SCRUMIT_PROJECT_ROLE_ON_PROJECT foreign key (PROJECT_ID) references SCRUMIT_TASK(ID);
alter table SCRUMIT_PROJECT_ROLE add constraint FK_SCRUMIT_PROJECT_ROLE_ON_PERFORMER foreign key (PERFORMER_ID) references SEC_USER(ID);
create index IDX_SCRUMIT_PROJECT_ROLE_ON_TEAM on SCRUMIT_PROJECT_ROLE (TEAM_ID);
create index IDX_SCRUMIT_PROJECT_ROLE_ON_PROJECT on SCRUMIT_PROJECT_ROLE (PROJECT_ID);
create index IDX_SCRUMIT_PROJECT_ROLE_ON_PERFORMER on SCRUMIT_PROJECT_ROLE (PERFORMER_ID);
