alter table SCRUMIT_PROJECT_IDENTIFICATOR add constraint FK_SCRUMIT_PROJECT_IDENTIFICATOR_PROJECT foreign key (PROJECT_ID) references SCRUMIT_TASK(ID);
create unique index IDX_SCRUMIT_PROJECT_IDENTIFICATOR_UK_IDENTIFICATOR on SCRUMIT_PROJECT_IDENTIFICATOR (IDENTIFICATOR) where DELETE_TS is null ;
