alter table SCRUMIT_TRACKER_FILE_DESCRIPTOR_LINK add constraint FK_TRAFILDES_ON_TRACKER foreign key (TRACKER_ID) references SCRUMIT_TRACKER(ID);
alter table SCRUMIT_TRACKER_FILE_DESCRIPTOR_LINK add constraint FK_TRAFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
