alter table SCRUMIT_MESSAGE add constraint FK_SCRUMIT_MESSAGE_DISCUSSION foreign key (DISCUSSION_ID) references SCRUMIT_DISCUSSION(ID);
alter table SCRUMIT_MESSAGE add constraint FK_SCRUMIT_MESSAGE_AUTOR foreign key (AUTOR_ID) references SEC_USER(ID);
alter table SCRUMIT_MESSAGE add constraint FK_SCRUMIT_MESSAGE_ATTACHMENT foreign key (ATTACHMENT_ID) references SYS_FILE(ID);
create index IDX_SCRUMIT_MESSAGE_DISCUSSION on SCRUMIT_MESSAGE (DISCUSSION_ID);
create index IDX_SCRUMIT_MESSAGE_AUTOR on SCRUMIT_MESSAGE (AUTOR_ID);
