alter table SCRUMIT_DISCUSSION add constraint FK_SCRUMIT_DISCUSSION_TRACKER foreign key (TRACKER_ID) references SCRUMIT_TRACKER(ID);
alter table SCRUMIT_DISCUSSION add constraint FK_SCRUMIT_DISCUSSION_INITIATOR foreign key (INITIATOR_ID) references SEC_USER(ID);
create index IDX_SCRUMIT_DISCUSSION_INITIATOR on SCRUMIT_DISCUSSION (INITIATOR_ID);
